### PR TITLE
Restore MG2 compatibility in onQueueComplete

### PR DESCRIPTION
**Pull request by ghidinelli**
Aborting the current handler and short-circuiting to exception handler ignores onQueueComplete. This broke compatibility with MG2.  We should expect onQueueComplete to fire consistently whether it is after a standard event handler or an exception event handler.

A common use case would be to share presentation configuration information that is not required until all other processing is complete, e.g.:

```
<event-handler name="ModelGlue.onQueueComplete">
    <broadcasts>
        <message name="needSiteTheme" />
    </broadcasts>
</event-handler>
```

Why put it in onQueueComplete?  Consider that some other processing might determine which theme to display in a themeable system.

### CODE REVIEW

**Comment by ghidinelli** [comment]
Thought I would mention that I've run this in production for ~2 years using it on most requests and it works great.

**Comment by dskaggs** [comment]
Brian...this looks fine to me. However, we need this to be merged into the newScaffolding branch as that's what we're working off of as a bleeding edge branch right now and what the next build will be based off of.  If you'd like, you can resubmit it that way, or if that's more trouble than it's worth, I can take the 1 line that you added and manually put it into the file in newScaffolding. Just let me know which way you'd like to go.

**Comment by ghidinelli** [comment]
It's fine with me if you want to just merge in the line.  

Can this branch be merged back into master?   I think it has outlived it's usefulness for scaffolding and it would be good to have a solid master with per-feature branching as needed.

**Comment by dskaggs** [comment]
Ok - I’ll get this updated later today (I’m traveling this week so my schedule is a little weird).

We are going to do a bunch of cleanup on the branches and get it to more of a standard layout but were trying to nail down this reload bug that relates to issue #1 but I think we can go ahead and do the reorg now. I’ll talk to Dan W and coordinate.

Thanks a bunch for everything!
Dan

**Comment by dskaggs** [comment]
Brian…this has been committed to the newScaffolding branch. Sorry this took a while. I was out of town last week.

I’m hoping to get the branch reorg done in the next week sometime.

Thanks
Dan

**Pull request closed without merging**
